version: '3.3'

services:
   web:
      build: .
      command: python /code/manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/code
      ports:
         - 8000:8000
      depends_on:
         -  db
      restart: "on-failure"
      env_file:
         -  ./.env

   db:
      image: library/postgres:13-alpine
      volumes:
         -  postgres_data:/var/lib/postrgresql/data/
      env_file:
         -  ./.env.db

volumes:
   postgres_data: